apiVersion: v1
kind: Service
metadata:
  name: juice-shop
  namespace: juice-shop-wiz
  labels:
    app: juice-shop
spec:
  type: LoadBalancer
  selector:
    app: juice-shop
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
